language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - python setup.py -q install
script:
  - py.test tests
